//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from F:/Workspace/Cobra/Frontend/Cobra.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CobraParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ICobraVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] CobraParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.linkStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLinkStatement([NotNull] CobraParser.LinkStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportStatement([NotNull] CobraParser.ImportStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.namespaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceDeclaration([NotNull] CobraParser.NamespaceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedName([NotNull] CobraParser.QualifiedNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.topLevelDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopLevelDeclaration([NotNull] CobraParser.TopLevelDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.constDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstDeclaration([NotNull] CobraParser.ConstDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.varDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDeclaration([NotNull] CobraParser.VarDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaration([NotNull] CobraParser.FunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.externDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternDeclaration([NotNull] CobraParser.ExternDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] CobraParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveType([NotNull] CobraParser.PrimitiveTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] CobraParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] CobraParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CobraParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationStatement([NotNull] CobraParser.DeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] CobraParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] CobraParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] CobraParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoWhileStatement([NotNull] CobraParser.DoWhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] CobraParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.forEachStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachStatement([NotNull] CobraParser.ForEachStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatement([NotNull] CobraParser.SwitchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.switchBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchBlock([NotNull] CobraParser.SwitchBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchLabel([NotNull] CobraParser.SwitchLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.tryStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryStatement([NotNull] CobraParser.TryStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJumpStatement([NotNull] CobraParser.JumpStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] CobraParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStatement([NotNull] CobraParser.PrintStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentExpression([NotNull] CobraParser.AssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.binaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryExpression([NotNull] CobraParser.BinaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOp([NotNull] CobraParser.UnaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixExpression([NotNull] CobraParser.PostfixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.leftHandSide"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeftHandSide([NotNull] CobraParser.LeftHandSideContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] CobraParser.PrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] CobraParser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionExpression([NotNull] CobraParser.FunctionExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.arrayLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayLiteral([NotNull] CobraParser.ArrayLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.dictLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictLiteral([NotNull] CobraParser.DictLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.dictEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictEntry([NotNull] CobraParser.DictEntryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] CobraParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CobraParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentOperator([NotNull] CobraParser.AssignmentOperatorContext context);
}
