//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/sujal/Code/Cobra/Frontend/Cobra.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CobraParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ICobraListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] CobraParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] CobraParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDeclaration([NotNull] CobraParser.ClassDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDeclaration([NotNull] CobraParser.ClassDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBody([NotNull] CobraParser.ClassBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBody([NotNull] CobraParser.ClassBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberDeclaration([NotNull] CobraParser.MemberDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberDeclaration([NotNull] CobraParser.MemberDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldDeclaration([NotNull] CobraParser.FieldDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldDeclaration([NotNull] CobraParser.FieldDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDeclaration([NotNull] CobraParser.MethodDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDeclaration([NotNull] CobraParser.MethodDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorDeclaration([NotNull] CobraParser.ConstructorDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorDeclaration([NotNull] CobraParser.ConstructorDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.externDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExternDeclaration([NotNull] CobraParser.ExternDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.externDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExternDeclaration([NotNull] CobraParser.ExternDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclaration([NotNull] CobraParser.FunctionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclaration([NotNull] CobraParser.FunctionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationStatement([NotNull] CobraParser.DeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationStatement([NotNull] CobraParser.DeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CobraParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CobraParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] CobraParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] CobraParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentOperator([NotNull] CobraParser.AssignmentOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentOperator([NotNull] CobraParser.AssignmentOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] CobraParser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] CobraParser.ExpressionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] CobraParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] CobraParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] CobraParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] CobraParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoWhileStatement([NotNull] CobraParser.DoWhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoWhileStatement([NotNull] CobraParser.DoWhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] CobraParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] CobraParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForControl([NotNull] CobraParser.ForControlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForControl([NotNull] CobraParser.ForControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStatement([NotNull] CobraParser.SwitchStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStatement([NotNull] CobraParser.SwitchStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.switchBlockStatementGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchBlockStatementGroup([NotNull] CobraParser.SwitchBlockStatementGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.switchBlockStatementGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchBlockStatementGroup([NotNull] CobraParser.SwitchBlockStatementGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchLabel([NotNull] CobraParser.SwitchLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchLabel([NotNull] CobraParser.SwitchLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpStatement([NotNull] CobraParser.JumpStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpStatement([NotNull] CobraParser.JumpStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CobraParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CobraParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpression([NotNull] CobraParser.AssignmentExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpression([NotNull] CobraParser.AssignmentExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalExpression([NotNull] CobraParser.ConditionalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalExpression([NotNull] CobraParser.ConditionalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpression([NotNull] CobraParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpression([NotNull] CobraParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpression([NotNull] CobraParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpression([NotNull] CobraParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.bitwiseOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwiseOrExpression([NotNull] CobraParser.BitwiseOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.bitwiseOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwiseOrExpression([NotNull] CobraParser.BitwiseOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.bitwiseXorExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwiseXorExpression([NotNull] CobraParser.BitwiseXorExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.bitwiseXorExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwiseXorExpression([NotNull] CobraParser.BitwiseXorExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.bitwiseAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwiseAndExpression([NotNull] CobraParser.BitwiseAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.bitwiseAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwiseAndExpression([NotNull] CobraParser.BitwiseAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpression([NotNull] CobraParser.EqualityExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpression([NotNull] CobraParser.EqualityExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.comparisonExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparisonExpression([NotNull] CobraParser.ComparisonExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.comparisonExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparisonExpression([NotNull] CobraParser.ComparisonExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.bitwiseShiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwiseShiftExpression([NotNull] CobraParser.BitwiseShiftExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.bitwiseShiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwiseShiftExpression([NotNull] CobraParser.BitwiseShiftExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] CobraParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] CobraParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] CobraParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] CobraParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] CobraParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] CobraParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExpression([NotNull] CobraParser.PostfixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExpression([NotNull] CobraParser.PostfixExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] CobraParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] CobraParser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] CobraParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] CobraParser.ArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] CobraParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] CobraParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpecifier([NotNull] CobraParser.TypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpecifier([NotNull] CobraParser.TypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveType([NotNull] CobraParser.PrimitiveTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveType([NotNull] CobraParser.PrimitiveTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] CobraParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] CobraParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] CobraParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] CobraParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessModifier([NotNull] CobraParser.AccessModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessModifier([NotNull] CobraParser.AccessModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportStatement([NotNull] CobraParser.ImportStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportStatement([NotNull] CobraParser.ImportStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] CobraParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] CobraParser.LiteralContext context);
}
