//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/sujal/Code/Cobra/Grammar/CobraParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CobraParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ICobraParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] CobraParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] CobraParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CobraParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CobraParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationStatement([NotNull] CobraParser.DeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationStatement([NotNull] CobraParser.DeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentStatement([NotNull] CobraParser.AssignmentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentStatement([NotNull] CobraParser.AssignmentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] CobraParser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] CobraParser.ExpressionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CobraParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CobraParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpression([NotNull] CobraParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpression([NotNull] CobraParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpression([NotNull] CobraParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpression([NotNull] CobraParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.comparisonExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparisonExpression([NotNull] CobraParser.ComparisonExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.comparisonExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparisonExpression([NotNull] CobraParser.ComparisonExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.arithmeticExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticExpression([NotNull] CobraParser.ArithmeticExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.arithmeticExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticExpression([NotNull] CobraParser.ArithmeticExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.multiplicationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicationExpression([NotNull] CobraParser.MultiplicationExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.multiplicationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicationExpression([NotNull] CobraParser.MultiplicationExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] CobraParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] CobraParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] CobraParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] CobraParser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.controlStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlStatement([NotNull] CobraParser.ControlStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.controlStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlStatement([NotNull] CobraParser.ControlStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] CobraParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] CobraParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileLoop([NotNull] CobraParser.WhileLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileLoop([NotNull] CobraParser.WhileLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForLoop([NotNull] CobraParser.ForLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForLoop([NotNull] CobraParser.ForLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.rangeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeExpression([NotNull] CobraParser.RangeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.rangeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeExpression([NotNull] CobraParser.RangeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] CobraParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] CobraParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclaration([NotNull] CobraParser.FunctionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclaration([NotNull] CobraParser.FunctionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] CobraParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] CobraParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] CobraParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] CobraParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] CobraParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] CobraParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] CobraParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] CobraParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] CobraParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] CobraParser.ArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] CobraParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] CobraParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CobraParser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportStatement([NotNull] CobraParser.ImportStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CobraParser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportStatement([NotNull] CobraParser.ImportStatementContext context);
}
