### YamlMime:ManagedReference
items:
- uid: Cobra.Environment.CobraEnum
  commentId: T:Cobra.Environment.CobraEnum
  id: CobraEnum
  parent: Cobra.Environment
  children:
  - Cobra.Environment.CobraEnum.#ctor(System.String,System.Collections.Generic.Dictionary{System.String,Cobra.Environment.CobraEnumMember})
  - Cobra.Environment.CobraEnum.Members
  - Cobra.Environment.CobraEnum.Name
  - Cobra.Environment.CobraEnum.ToString
  langs:
  - csharp
  - vb
  name: CobraEnum
  nameWithType: CobraEnum
  fullName: Cobra.Environment.CobraEnum
  type: Class
  source:
    remote:
      path: Environment/CobraEnum.cs
      branch: main
      repo: https://github.com/SujalChoudhari/Cobra.git
    id: CobraEnum
    path: ../Environment/CobraEnum.cs
    startLine: 2
  assemblies:
  - Cobra
  namespace: Cobra.Environment
  syntax:
    content: public class CobraEnum
    content.vb: Public Class CobraEnum
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: Cobra.Environment.CobraEnum.#ctor(System.String,System.Collections.Generic.Dictionary{System.String,Cobra.Environment.CobraEnumMember})
  commentId: M:Cobra.Environment.CobraEnum.#ctor(System.String,System.Collections.Generic.Dictionary{System.String,Cobra.Environment.CobraEnumMember})
  id: '#ctor(System.String,System.Collections.Generic.Dictionary{System.String,Cobra.Environment.CobraEnumMember})'
  parent: Cobra.Environment.CobraEnum
  langs:
  - csharp
  - vb
  name: CobraEnum(string, Dictionary<string, CobraEnumMember>)
  nameWithType: CobraEnum.CobraEnum(string, Dictionary<string, CobraEnumMember>)
  fullName: Cobra.Environment.CobraEnum.CobraEnum(string, System.Collections.Generic.Dictionary<string, Cobra.Environment.CobraEnumMember>)
  type: Constructor
  source:
    remote:
      path: Environment/CobraEnum.cs
      branch: main
      repo: https://github.com/SujalChoudhari/Cobra.git
    id: .ctor
    path: ../Environment/CobraEnum.cs
    startLine: 2
  assemblies:
  - Cobra
  namespace: Cobra.Environment
  syntax:
    content: public CobraEnum(string name, Dictionary<string, CobraEnumMember> members)
    parameters:
    - id: name
      type: System.String
    - id: members
      type: System.Collections.Generic.Dictionary{System.String,Cobra.Environment.CobraEnumMember}
    content.vb: Public Sub New(name As String, members As Dictionary(Of String, CobraEnumMember))
  overload: Cobra.Environment.CobraEnum.#ctor*
  nameWithType.vb: CobraEnum.New(String, Dictionary(Of String, CobraEnumMember))
  fullName.vb: Cobra.Environment.CobraEnum.New(String, System.Collections.Generic.Dictionary(Of String, Cobra.Environment.CobraEnumMember))
  name.vb: New(String, Dictionary(Of String, CobraEnumMember))
- uid: Cobra.Environment.CobraEnum.Name
  commentId: P:Cobra.Environment.CobraEnum.Name
  id: Name
  parent: Cobra.Environment.CobraEnum
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: CobraEnum.Name
  fullName: Cobra.Environment.CobraEnum.Name
  type: Property
  source:
    remote:
      path: Environment/CobraEnum.cs
      branch: main
      repo: https://github.com/SujalChoudhari/Cobra.git
    id: Name
    path: ../Environment/CobraEnum.cs
    startLine: 4
  assemblies:
  - Cobra
  namespace: Cobra.Environment
  syntax:
    content: public string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Name As String
  overload: Cobra.Environment.CobraEnum.Name*
- uid: Cobra.Environment.CobraEnum.Members
  commentId: P:Cobra.Environment.CobraEnum.Members
  id: Members
  parent: Cobra.Environment.CobraEnum
  langs:
  - csharp
  - vb
  name: Members
  nameWithType: CobraEnum.Members
  fullName: Cobra.Environment.CobraEnum.Members
  type: Property
  source:
    remote:
      path: Environment/CobraEnum.cs
      branch: main
      repo: https://github.com/SujalChoudhari/Cobra.git
    id: Members
    path: ../Environment/CobraEnum.cs
    startLine: 5
  assemblies:
  - Cobra
  namespace: Cobra.Environment
  syntax:
    content: public Dictionary<string, CobraEnumMember> Members { get; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.String,Cobra.Environment.CobraEnumMember}
    content.vb: Public ReadOnly Property Members As Dictionary(Of String, CobraEnumMember)
  overload: Cobra.Environment.CobraEnum.Members*
- uid: Cobra.Environment.CobraEnum.ToString
  commentId: M:Cobra.Environment.CobraEnum.ToString
  id: ToString
  parent: Cobra.Environment.CobraEnum
  langs:
  - csharp
  - vb
  name: ToString()
  nameWithType: CobraEnum.ToString()
  fullName: Cobra.Environment.CobraEnum.ToString()
  type: Method
  source:
    remote:
      path: Environment/CobraEnum.cs
      branch: main
      repo: https://github.com/SujalChoudhari/Cobra.git
    id: ToString
    path: ../Environment/CobraEnum.cs
    startLine: 7
  assemblies:
  - Cobra
  namespace: Cobra.Environment
  summary: Returns a string that represents the current object.
  example: []
  syntax:
    content: public override string ToString()
    return:
      type: System.String
      description: A string that represents the current object.
    content.vb: Public Overrides Function ToString() As String
  overridden: System.Object.ToString
  overload: Cobra.Environment.CobraEnum.ToString*
references:
- uid: Cobra.Environment
  commentId: N:Cobra.Environment
  href: Cobra.html
  name: Cobra.Environment
  nameWithType: Cobra.Environment
  fullName: Cobra.Environment
  spec.csharp:
  - uid: Cobra
    name: Cobra
    href: Cobra.html
  - name: .
  - uid: Cobra.Environment
    name: Environment
    href: Cobra.Environment.html
  spec.vb:
  - uid: Cobra
    name: Cobra
    href: Cobra.html
  - name: .
  - uid: Cobra.Environment
    name: Environment
    href: Cobra.Environment.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Cobra.Environment.CobraEnum.#ctor*
  commentId: Overload:Cobra.Environment.CobraEnum.#ctor
  href: Cobra.Environment.CobraEnum.html#Cobra_Environment_CobraEnum__ctor_System_String_System_Collections_Generic_Dictionary_System_String_Cobra_Environment_CobraEnumMember__
  name: CobraEnum
  nameWithType: CobraEnum.CobraEnum
  fullName: Cobra.Environment.CobraEnum.CobraEnum
  nameWithType.vb: CobraEnum.New
  fullName.vb: Cobra.Environment.CobraEnum.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Collections.Generic.Dictionary{System.String,Cobra.Environment.CobraEnumMember}
  commentId: T:System.Collections.Generic.Dictionary{System.String,Cobra.Environment.CobraEnumMember}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<string, CobraEnumMember>
  nameWithType: Dictionary<string, CobraEnumMember>
  fullName: System.Collections.Generic.Dictionary<string, Cobra.Environment.CobraEnumMember>
  nameWithType.vb: Dictionary(Of String, CobraEnumMember)
  fullName.vb: System.Collections.Generic.Dictionary(Of String, Cobra.Environment.CobraEnumMember)
  name.vb: Dictionary(Of String, CobraEnumMember)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: Cobra.Environment.CobraEnumMember
    name: CobraEnumMember
    href: Cobra.Environment.CobraEnumMember.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: Cobra.Environment.CobraEnumMember
    name: CobraEnumMember
    href: Cobra.Environment.CobraEnumMember.html
  - name: )
- uid: System.Collections.Generic.Dictionary`2
  commentId: T:System.Collections.Generic.Dictionary`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<TKey, TValue>
  nameWithType: Dictionary<TKey, TValue>
  fullName: System.Collections.Generic.Dictionary<TKey, TValue>
  nameWithType.vb: Dictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.Dictionary(Of TKey, TValue)
  name.vb: Dictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Cobra.Environment.CobraEnum.Name*
  commentId: Overload:Cobra.Environment.CobraEnum.Name
  href: Cobra.Environment.CobraEnum.html#Cobra_Environment_CobraEnum_Name
  name: Name
  nameWithType: CobraEnum.Name
  fullName: Cobra.Environment.CobraEnum.Name
- uid: Cobra.Environment.CobraEnum.Members*
  commentId: Overload:Cobra.Environment.CobraEnum.Members
  href: Cobra.Environment.CobraEnum.html#Cobra_Environment_CobraEnum_Members
  name: Members
  nameWithType: CobraEnum.Members
  fullName: Cobra.Environment.CobraEnum.Members
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: Cobra.Environment.CobraEnum.ToString*
  commentId: Overload:Cobra.Environment.CobraEnum.ToString
  href: Cobra.Environment.CobraEnum.html#Cobra_Environment_CobraEnum_ToString
  name: ToString
  nameWithType: CobraEnum.ToString
  fullName: Cobra.Environment.CobraEnum.ToString
