### YamlMime:ManagedReference
items:
- uid: Cobra.Environment.CobraEnumMember
  commentId: T:Cobra.Environment.CobraEnumMember
  id: CobraEnumMember
  parent: Cobra.Environment
  children:
  - Cobra.Environment.CobraEnumMember.#ctor(System.String,System.Int64,Cobra.Environment.CobraEnum)
  - Cobra.Environment.CobraEnumMember.EnumType
  - Cobra.Environment.CobraEnumMember.Name
  - Cobra.Environment.CobraEnumMember.ToString
  - Cobra.Environment.CobraEnumMember.Value
  langs:
  - csharp
  - vb
  name: CobraEnumMember
  nameWithType: CobraEnumMember
  fullName: Cobra.Environment.CobraEnumMember
  type: Class
  source:
    remote:
      path: Environment/CobraEnumMember.cs
      branch: main
      repo: https://github.com/SujalChoudhari/Cobra.git
    id: CobraEnumMember
    path: ../Environment/CobraEnumMember.cs
    startLine: 2
  assemblies:
  - Cobra
  namespace: Cobra.Environment
  syntax:
    content: public class CobraEnumMember
    content.vb: Public Class CobraEnumMember
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: Cobra.Environment.CobraEnumMember.#ctor(System.String,System.Int64,Cobra.Environment.CobraEnum)
  commentId: M:Cobra.Environment.CobraEnumMember.#ctor(System.String,System.Int64,Cobra.Environment.CobraEnum)
  id: '#ctor(System.String,System.Int64,Cobra.Environment.CobraEnum)'
  parent: Cobra.Environment.CobraEnumMember
  langs:
  - csharp
  - vb
  name: CobraEnumMember(string, long, CobraEnum)
  nameWithType: CobraEnumMember.CobraEnumMember(string, long, CobraEnum)
  fullName: Cobra.Environment.CobraEnumMember.CobraEnumMember(string, long, Cobra.Environment.CobraEnum)
  type: Constructor
  source:
    remote:
      path: Environment/CobraEnumMember.cs
      branch: main
      repo: https://github.com/SujalChoudhari/Cobra.git
    id: .ctor
    path: ../Environment/CobraEnumMember.cs
    startLine: 2
  assemblies:
  - Cobra
  namespace: Cobra.Environment
  syntax:
    content: public CobraEnumMember(string name, long value, CobraEnum enumType)
    parameters:
    - id: name
      type: System.String
    - id: value
      type: System.Int64
    - id: enumType
      type: Cobra.Environment.CobraEnum
    content.vb: Public Sub New(name As String, value As Long, enumType As CobraEnum)
  overload: Cobra.Environment.CobraEnumMember.#ctor*
  nameWithType.vb: CobraEnumMember.New(String, Long, CobraEnum)
  fullName.vb: Cobra.Environment.CobraEnumMember.New(String, Long, Cobra.Environment.CobraEnum)
  name.vb: New(String, Long, CobraEnum)
- uid: Cobra.Environment.CobraEnumMember.Name
  commentId: P:Cobra.Environment.CobraEnumMember.Name
  id: Name
  parent: Cobra.Environment.CobraEnumMember
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: CobraEnumMember.Name
  fullName: Cobra.Environment.CobraEnumMember.Name
  type: Property
  source:
    remote:
      path: Environment/CobraEnumMember.cs
      branch: main
      repo: https://github.com/SujalChoudhari/Cobra.git
    id: Name
    path: ../Environment/CobraEnumMember.cs
    startLine: 4
  assemblies:
  - Cobra
  namespace: Cobra.Environment
  syntax:
    content: public string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Name As String
  overload: Cobra.Environment.CobraEnumMember.Name*
- uid: Cobra.Environment.CobraEnumMember.Value
  commentId: P:Cobra.Environment.CobraEnumMember.Value
  id: Value
  parent: Cobra.Environment.CobraEnumMember
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: CobraEnumMember.Value
  fullName: Cobra.Environment.CobraEnumMember.Value
  type: Property
  source:
    remote:
      path: Environment/CobraEnumMember.cs
      branch: main
      repo: https://github.com/SujalChoudhari/Cobra.git
    id: Value
    path: ../Environment/CobraEnumMember.cs
    startLine: 5
  assemblies:
  - Cobra
  namespace: Cobra.Environment
  syntax:
    content: public long Value { get; }
    parameters: []
    return:
      type: System.Int64
    content.vb: Public ReadOnly Property Value As Long
  overload: Cobra.Environment.CobraEnumMember.Value*
- uid: Cobra.Environment.CobraEnumMember.EnumType
  commentId: P:Cobra.Environment.CobraEnumMember.EnumType
  id: EnumType
  parent: Cobra.Environment.CobraEnumMember
  langs:
  - csharp
  - vb
  name: EnumType
  nameWithType: CobraEnumMember.EnumType
  fullName: Cobra.Environment.CobraEnumMember.EnumType
  type: Property
  source:
    remote:
      path: Environment/CobraEnumMember.cs
      branch: main
      repo: https://github.com/SujalChoudhari/Cobra.git
    id: EnumType
    path: ../Environment/CobraEnumMember.cs
    startLine: 6
  assemblies:
  - Cobra
  namespace: Cobra.Environment
  syntax:
    content: public CobraEnum EnumType { get; }
    parameters: []
    return:
      type: Cobra.Environment.CobraEnum
    content.vb: Public ReadOnly Property EnumType As CobraEnum
  overload: Cobra.Environment.CobraEnumMember.EnumType*
- uid: Cobra.Environment.CobraEnumMember.ToString
  commentId: M:Cobra.Environment.CobraEnumMember.ToString
  id: ToString
  parent: Cobra.Environment.CobraEnumMember
  langs:
  - csharp
  - vb
  name: ToString()
  nameWithType: CobraEnumMember.ToString()
  fullName: Cobra.Environment.CobraEnumMember.ToString()
  type: Method
  source:
    remote:
      path: Environment/CobraEnumMember.cs
      branch: main
      repo: https://github.com/SujalChoudhari/Cobra.git
    id: ToString
    path: ../Environment/CobraEnumMember.cs
    startLine: 8
  assemblies:
  - Cobra
  namespace: Cobra.Environment
  summary: Returns a string that represents the current object.
  example: []
  syntax:
    content: public override string ToString()
    return:
      type: System.String
      description: A string that represents the current object.
    content.vb: Public Overrides Function ToString() As String
  overridden: System.Object.ToString
  overload: Cobra.Environment.CobraEnumMember.ToString*
references:
- uid: Cobra.Environment
  commentId: N:Cobra.Environment
  href: Cobra.html
  name: Cobra.Environment
  nameWithType: Cobra.Environment
  fullName: Cobra.Environment
  spec.csharp:
  - uid: Cobra
    name: Cobra
    href: Cobra.html
  - name: .
  - uid: Cobra.Environment
    name: Environment
    href: Cobra.Environment.html
  spec.vb:
  - uid: Cobra
    name: Cobra
    href: Cobra.html
  - name: .
  - uid: Cobra.Environment
    name: Environment
    href: Cobra.Environment.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Cobra.Environment.CobraEnumMember.#ctor*
  commentId: Overload:Cobra.Environment.CobraEnumMember.#ctor
  href: Cobra.Environment.CobraEnumMember.html#Cobra_Environment_CobraEnumMember__ctor_System_String_System_Int64_Cobra_Environment_CobraEnum_
  name: CobraEnumMember
  nameWithType: CobraEnumMember.CobraEnumMember
  fullName: Cobra.Environment.CobraEnumMember.CobraEnumMember
  nameWithType.vb: CobraEnumMember.New
  fullName.vb: Cobra.Environment.CobraEnumMember.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int64
  name: long
  nameWithType: long
  fullName: long
  nameWithType.vb: Long
  fullName.vb: Long
  name.vb: Long
- uid: Cobra.Environment.CobraEnum
  commentId: T:Cobra.Environment.CobraEnum
  parent: Cobra.Environment
  href: Cobra.Environment.CobraEnum.html
  name: CobraEnum
  nameWithType: CobraEnum
  fullName: Cobra.Environment.CobraEnum
- uid: Cobra.Environment.CobraEnumMember.Name*
  commentId: Overload:Cobra.Environment.CobraEnumMember.Name
  href: Cobra.Environment.CobraEnumMember.html#Cobra_Environment_CobraEnumMember_Name
  name: Name
  nameWithType: CobraEnumMember.Name
  fullName: Cobra.Environment.CobraEnumMember.Name
- uid: Cobra.Environment.CobraEnumMember.Value*
  commentId: Overload:Cobra.Environment.CobraEnumMember.Value
  href: Cobra.Environment.CobraEnumMember.html#Cobra_Environment_CobraEnumMember_Value
  name: Value
  nameWithType: CobraEnumMember.Value
  fullName: Cobra.Environment.CobraEnumMember.Value
- uid: Cobra.Environment.CobraEnumMember.EnumType*
  commentId: Overload:Cobra.Environment.CobraEnumMember.EnumType
  href: Cobra.Environment.CobraEnumMember.html#Cobra_Environment_CobraEnumMember_EnumType
  name: EnumType
  nameWithType: CobraEnumMember.EnumType
  fullName: Cobra.Environment.CobraEnumMember.EnumType
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: Cobra.Environment.CobraEnumMember.ToString*
  commentId: Overload:Cobra.Environment.CobraEnumMember.ToString
  href: Cobra.Environment.CobraEnumMember.html#Cobra_Environment_CobraEnumMember_ToString
  name: ToString
  nameWithType: CobraEnumMember.ToString
  fullName: Cobra.Environment.CobraEnumMember.ToString
